### PR TITLE
fix: Fix literal quote in Formatter

### PR DESCRIPTION
**Pull request by theanht1**

### CODE REVIEW

**Comment by amolk** [comment]
@theanht1 I googled for single quote in SQL and came across this -- https://stackoverflow.com/questions/1586560/how-do-i-escape-a-single-quote-in-sql-server. It suggests that doubling the single quote is how SQL escapes it.

**Comment by theanht1** [comment]
@amolk Yeah, it seems like doubling quote is supported by most of the SQL DBMS, but not for [Google Bigquery](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#literals). So I think we should make this literal quote as an optional param of Formatter, support both types of escaping

**Comment by theanht1** [comment]
@amolk I've updated so slash quote is an optional param, plz review this

**Review by amolk — APPROVED** [review]
Looks good. Thank you for the PR.

**Pull request merged**
