### PR TITLE
Update mozilla upstream and wrap compound operator in `from` key

### PR DESCRIPTION
**Pull request by theanht1**

### CODE REVIEW

**Review by amolk — APPROVED** [review]

**Comment by theanht1** [comment]
@amolk if there are no issues, please merge this PR so we can finish integration for v0.6

**Comment by amolk** [comment]
@theanht1 Please rebase and resolve merge conflicts so it can be merged

**Comment by theanht1** [comment]
@amolk I've merged your dev branch into this. If you want to rebase new commits, I'll create a new PR, wdyt?

**Comment by amolk** [comment]
Done

**Comment by theanht1** [comment]
Thanks 👍

**Pull request merged**
